from typing import Any

def input(filename: str, **kwargs: Any) -> Stream: ...
def output(*inputs: Any, filename: str, **kwargs: Any) -> Stream: ...
def probe(filename: str) -> dict[str, Any]: ...

class Stream:
    @property
    def video(self) -> Stream: ...
    @property
    def audio(self) -> Stream: ...
    def filter(self, name: str, *args: Any, **kwargs: Any) -> Stream: ...
    def output(self, filename: str, **kwargs: Any) -> Stream: ...
    def overwrite_output(self) -> Stream: ...
    def run(
        self,
        capture_stdout: bool = ...,
        capture_stderr: bool = ...,
    ) -> tuple[Any, Any]: ...

class Error(Exception):
    stderr: bytes | None
