from typing import Optional

class EdgeTTSException(Exception): ...
class NoAudioReceived(EdgeTTSException): ...
class UnexpectedResponse(EdgeTTSException): ...
class UnknownResponse(EdgeTTSException): ...
class WebSocketError(EdgeTTSException): ...
class SkewAdjustmentError(EdgeTTSException): ...

class Communicate:
    def __init__(
        self,
        text: str,
        voice: str = ...,
        *,
        rate: str = ...,
        volume: str = ...,
        pitch: str = ...,
        boundary: str = ...,
        connector: Optional[object] = ...,
        proxy: Optional[str] = ...,
        connect_timeout: Optional[int] = ...,
        receive_timeout: Optional[int] = ...,
    ) -> None: ...
    def save_sync(self, audio_fname: str, metadata_fname: Optional[str] = None) -> None: ...
