class EdgeTTSException(Exception): ...
class NoAudioReceived(EdgeTTSException): ...
class UnexpectedResponse(EdgeTTSException): ...
class UnknownResponse(EdgeTTSException): ...
class WebSocketError(EdgeTTSException): ...
class SkewAdjustmentError(EdgeTTSException): ...
